version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-php
    image: backend-php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge